#!/usr/bin/env python3
"""Moves the dynamic vehicle, and publishes ground truth for both obstacles.

SIMULATION ONLY. Nothing in the landing pipeline may subscribe to what this
publishes. The point of the trajectory work is that the aircraft infers where
an obstacle is going from its own camera; handing it the answer would measure
nothing. `/eland/obstacle_truth` exists so the estimator can be scored against
the truth afterwards, and it is named to make an accidental subscription
obvious in `ros2 node info`.

WHY TELEPORT INSTEAD OF PUSH

The vehicle is moved with the world's `set_pose` service rather than a
velocity command through the physics engine. Three reasons, in order of how
much they cost when ignored:

  1. A repeatable test needs a repeatable obstacle. Velocity control leaves
     the pose to friction, contact and solver iterations, so "the vehicle
     reaches the landing site at t=12 s" stops being true across runs and any
     timing measurement drifts with it.
  2. The obstacle must not be knocked around by the aircraft it is a hazard
     to. A physical 1.5 t box under a descending multicopter is a collision
     test, not a landing test.
  3. Nothing in the pipeline reads forces. The camera sees pixels, so pose is
     the whole interface.

Measured before choosing it: one set_pose call on a static labelled model
moved its segmentation blob from (100.7, 119.5) to (101.8, 212.6) px, so the
render path follows a teleported model and the label survives the move.

The walking person is NOT driven here -- it is a Gazebo <actor> whose waypoint
script owns its pose, generated by scripts/gen_world.py from the same
parameters. Gazebo publishes no pose for it (measured: neither pose/info nor
dynamic_pose/info lists an actor, while the segmentation camera plainly sees
it move), so its truth is computed from the same script, on the same sim
clock. That is a weaker guarantee than the vehicle's and is flagged where it
is computed.
"""
from __future__ import annotations

import math

from geometry_msgs.msg import Pose as RosPose
from geometry_msgs.msg import PoseArray
import rclpy
from rclpy.node import Node

from gz.msgs10.boolean_pb2 import Boolean
from gz.msgs10.pose_pb2 import Pose as GzPose
from gz.msgs10.world_stats_pb2 import WorldStatistics
from gz.transport13 import Node as GzNode


def _yaw_to_quat(yaw):
    return math.sin(yaw / 2.0), math.cos(yaw / 2.0)


class ObstacleDriver(Node):

    def __init__(self):
        super().__init__('obstacle_driver')

        self.declare_parameter('enable', True)
        self.declare_parameter('world_name', 'eland_test')
        self.declare_parameter('update_rate_hz', 20.0)
        self.declare_parameter('person_name', 'dyn_person')
        self.declare_parameter('person_kind', 'model')
        self.declare_parameter('person_start', [-10.0, -8.0])
        self.declare_parameter('person_goal', [10.0, -8.0])
        self.declare_parameter('person_speed', 1.2)
        self.declare_parameter('person_z', 1.0)
        self.declare_parameter('vehicle_name', 'dyn_vehicle')
        self.declare_parameter('vehicle_start', [20.0, 0.0])
        self.declare_parameter('vehicle_goal', [-20.0, 0.0])
        self.declare_parameter('vehicle_speed', 3.0)
        self.declare_parameter('vehicle_size', [4.4, 1.9, 1.5])
        self.declare_parameter('vehicle_mode', 'pingpong')
        self.declare_parameter('truth_topic', '/eland/obstacle_truth')

        gp = self.get_parameter
        self._enabled = gp('enable').value
        self._world = gp('world_name').value
        self._person_name = gp('person_name').value
        self._vehicle_name = gp('vehicle_name').value
        self._start = list(gp('vehicle_start').value)
        self._goal = list(gp('vehicle_goal').value)
        self._speed = float(gp('vehicle_speed').value)
        self._mode = gp('vehicle_mode').value
        self._z = float(gp('vehicle_size').value[2]) / 2.0
        rate = float(gp('update_rate_hz').value)

        self._leg = math.hypot(self._goal[0] - self._start[0],
                               self._goal[1] - self._start[1])
        self._leg_time = self._leg / self._speed if self._speed > 0 else 0.0
        self._yaw_out = math.atan2(self._goal[1] - self._start[1],
                                   self._goal[0] - self._start[0])

        self._gz = GzNode()
        self._service = f'/world/{self._world}/set_pose'

        # Sim time, from Gazebo's own statistics topic. Both obstacles are
        # placed on this clock rather than the wall clock so a run is
        # reproducible even if the real-time factor sags: the vehicle is where
        # the scenario says it is at sim second N, not at wall second N.
        self._sim_time = None
        self._real_time = None
        self._rtf_mark = None
        self._gz.subscribe(WorldStatistics, f'/world/{self._world}/stats',
                           self._on_stats)

        # The person is driven exactly like the vehicle when it is a model,
        # which is the default. When gen_world.py was told to emit an <actor>
        # instead, Gazebo's trajectory script owns the pose and these commands
        # are ignored -- the published truth is then the script's nominal
        # position, which was measured to run about 17% fast, so it is
        # flagged in the message rather than pretended to be exact.
        self._person_kind = gp('person_kind').value
        self._person_start = list(gp('person_start').value)
        self._person_goal = list(gp('person_goal').value)
        self._person_speed = float(gp('person_speed').value)
        self._person_z = float(gp('person_z').value)
        person_dist = math.hypot(self._person_goal[0] - self._person_start[0],
                                 self._person_goal[1] - self._person_start[1])
        self._person_leg_time = (person_dist / self._person_speed
                                 if self._person_speed > 0 else 0.0)

        self._truth_pub = self.create_publisher(
            PoseArray, gp('truth_topic').value, 10)

        self._vehicle_pose = (self._start[0], self._start[1], self._yaw_out)

        if not self._enabled:
            self.get_logger().warn(
                'obstacle_driver disabled by parameter; the world still '
                'contains whatever gen_world.py last wrote')
            return

        self.create_timer(1.0 / rate, self._tick)
        self.create_timer(10.0, self._log_rtf)
        self.get_logger().info(
            f'driving {self._vehicle_name} {self._start} -> {self._goal} at '
            f'{self._speed} m/s ({self._mode}), {self._leg_time:.1f} s per leg')

    # ------------------------------------------------------------------ gz io

    def _on_stats(self, msg):
        self._sim_time = msg.sim_time.sec + msg.sim_time.nsec * 1e-9
        self._real_time = msg.real_time.sec + msg.real_time.nsec * 1e-9

    def _log_rtf(self):
        """Report the real-time factor, because every speed in this system is
        quoted against one of two clocks and they are not the same one.

        The obstacles move on sim time -- so does the aircraft, so that is the
        clock the scenario is physically defined in. The perception chain
        stamps its frames with wall time, so tracker_node's velocities come
        out scaled by the real-time factor. Measured here rather than assumed,
        because on this machine the factor is well below 1 and a reader
        comparing an estimated 1.5 m/s against a configured 3.0 m/s deserves
        to see why before concluding the estimator is broken.
        """
        if self._sim_time is None or self._real_time is None:
            return
        if self._rtf_mark is None:
            self._rtf_mark = (self._sim_time, self._real_time)
            return
        d_sim = self._sim_time - self._rtf_mark[0]
        d_real = self._real_time - self._rtf_mark[1]
        self._rtf_mark = (self._sim_time, self._real_time)
        if d_real > 0.0:
            self.get_logger().info(
                f'real-time factor {d_sim / d_real:.2f} '
                f'(sim {self._sim_time:.1f} s); obstacles advance on sim time, '
                f'so their speed in wall-clock terms is that factor times the '
                f'configured value')

    def _person_heading(self, t):
        if self._person_leg_time <= 0.0:
            return 0.0
        phase = (t % (2.0 * self._person_leg_time)) / self._person_leg_time
        out = math.atan2(self._person_goal[1] - self._person_start[1],
                         self._person_goal[0] - self._person_start[0])
        return out if phase <= 1.0 else out + math.pi

    def _person_at(self, t):
        """Where the person is at sim time t.

        For the default `model` person this is the pose that gets commanded,
        so it is truth in the same sense as the vehicle's. For an `actor` it
        is only the script's nominal position, which Gazebo does not follow
        exactly -- see the note above.
        """
        if self._person_leg_time <= 0.0:
            return self._person_start[0], self._person_start[1]
        phase = (t % (2.0 * self._person_leg_time)) / self._person_leg_time
        frac = phase if phase <= 1.0 else 2.0 - phase
        x = self._person_start[0] + (self._person_goal[0] - self._person_start[0]) * frac
        y = self._person_start[1] + (self._person_goal[1] - self._person_start[1]) * frac
        return x, y

    def _set_pose(self, name, x, y, z, yaw):
        req = GzPose()
        req.name = name
        req.position.x = x
        req.position.y = y
        req.position.z = z
        qz, qw = _yaw_to_quat(yaw)
        req.orientation.z = qz
        req.orientation.w = qw
        ok, _ = self._gz.request(self._service, req, GzPose, Boolean, 200)
        return ok

    # ---------------------------------------------------------------- motion

    def _vehicle_at(self, t):
        """Pose on the leg at sim time t."""
        if self._leg_time <= 0.0:
            return self._start[0], self._start[1], self._yaw_out

        if self._mode == 'pingpong':
            phase = (t % (2.0 * self._leg_time)) / self._leg_time
            if phase <= 1.0:
                frac, yaw = phase, self._yaw_out
            else:
                frac, yaw = 2.0 - phase, self._yaw_out + math.pi
        else:
            frac = min(t / self._leg_time, 1.0)
            yaw = self._yaw_out

        x = self._start[0] + (self._goal[0] - self._start[0]) * frac
        y = self._start[1] + (self._goal[1] - self._start[1]) * frac
        return x, y, yaw

    def _tick(self):
        if self._sim_time is None:
            # No world statistics yet. Placing the vehicle on the wall clock
            # in the meantime would start the scenario at an offset nobody
            # asked for, so it stays at its spawn pose until Gazebo speaks.
            return
        x, y, yaw = self._vehicle_at(self._sim_time)
        self._vehicle_pose = (x, y, yaw)
        self._set_pose(self._vehicle_name, x, y, self._z, yaw)

        px, py = self._person_at(self._sim_time)
        if self._person_kind == 'model':
            # 0.9 m: half of the 1.8 m cylinder, so it stands on the ground
            # rather than half-buried, matching the static people.
            self._set_pose(self._person_name, px, py, 0.9,
                           self._person_heading(self._sim_time))
        self._publish_truth()

    def _publish_truth(self):
        """Both obstacles, vehicle first, person second. Order is the contract:
        a PoseArray has no names, and adding a message type for a topic that
        only exists to be plotted afterwards is not worth a new dependency in
        eland_msgs."""
        msg = PoseArray()
        msg.header.stamp = self.get_clock().now().to_msg()
        msg.header.frame_id = 'map'

        veh = RosPose()
        veh.position.x, veh.position.y = self._vehicle_pose[0], self._vehicle_pose[1]
        veh.position.z = self._z
        qz, qw = _yaw_to_quat(self._vehicle_pose[2])
        veh.orientation.z, veh.orientation.w = qz, qw
        msg.poses.append(veh)

        px, py = self._person_at(self._sim_time)
        per = RosPose()
        per.position.x, per.position.y, per.position.z = px, py, self._person_z
        per.orientation.w = 1.0
        msg.poses.append(per)

        self._truth_pub.publish(msg)


def main():
    rclpy.init()
    node = ObstacleDriver()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.try_shutdown()


if __name__ == '__main__':
    main()
