#!/usr/bin/env python3
"""Moves the dynamic vehicle, and publishes ground truth for both obstacles.

SIMULATION ONLY. Nothing in the landing pipeline may subscribe to what this
publishes. The point of the trajectory work is that the aircraft infers where
an obstacle is going from its own camera; handing it the answer would measure
nothing. `/eland/obstacle_truth` exists so the estimator can be scored against
the truth afterwards, and it is named to make an accidental subscription
obvious in `ros2 node info`.

WHY TELEPORT INSTEAD OF PUSH

The vehicle is moved with the world's `set_pose` service rather than a
velocity command through the physics engine. Three reasons, in order of how
much they cost when ignored:

  1. A repeatable test needs a repeatable obstacle. Velocity control leaves
     the pose to friction, contact and solver iterations, so "the vehicle
     reaches the landing site at t=12 s" stops being true across runs and any
     timing measurement drifts with it.
  2. The obstacle must not be knocked around by the aircraft it is a hazard
     to. A physical 1.5 t box under a descending multicopter is a collision
     test, not a landing test.
  3. Nothing in the pipeline reads forces. The camera sees pixels, so pose is
     the whole interface.

Measured before choosing it: one set_pose call on a static labelled model
moved its segmentation blob from (100.7, 119.5) to (101.8, 212.6) px, so the
render path follows a teleported model and the label survives the move.

The walking person is NOT driven here -- it is a Gazebo <actor> whose waypoint
script owns its pose, generated by scripts/gen_world.py from the same
parameters. Gazebo publishes no pose for it (measured: neither pose/info nor
dynamic_pose/info lists an actor, while the segmentation camera plainly sees
it move), so its truth is computed from the same script, on the same sim
clock. That is a weaker guarantee than the vehicle's and is flagged where it
is computed.
"""
from __future__ import annotations

import math
import os

from geometry_msgs.msg import Pose as RosPose
from geometry_msgs.msg import PoseArray
import rclpy
from rclpy.node import Node

from gz.msgs10.boolean_pb2 import Boolean
from gz.msgs10.pose_pb2 import Pose as GzPose
from gz.msgs10.world_stats_pb2 import WorldStatistics
from gz.transport13 import Node as GzNode


def _yaw_to_quat(yaw):
    return math.sin(yaw / 2.0), math.cos(yaw / 2.0)


class ObstacleDriver(Node):

    def __init__(self):
        super().__init__('obstacle_driver')

        self.declare_parameter('enable', True)
        self.declare_parameter('world_name', 'eland_test')
        self.declare_parameter('update_rate_hz', 20.0)
        self.declare_parameter('person_name', 'dyn_person')
        self.declare_parameter('person_kind', 'model')
        self.declare_parameter('person_start', [-10.0, -8.0])
        self.declare_parameter('person_goal', [10.0, -8.0])
        self.declare_parameter('person_speed', 1.2)
        self.declare_parameter('person_z', 1.0)
        self.declare_parameter('person_count', 1)
        self.declare_parameter('person_spacing_m', 6.0)
        self.declare_parameter('vehicle_name', 'dyn_vehicle')
        self.declare_parameter('vehicle_start', [20.0, 0.0])
        self.declare_parameter('vehicle_goal', [-20.0, 0.0])
        self.declare_parameter('vehicle_speed', 3.0)
        self.declare_parameter('vehicle_size', [4.4, 1.9, 1.5])
        self.declare_parameter('vehicle_mode', 'pingpong')
        self.declare_parameter('vehicle_count', 1)
        self.declare_parameter('vehicle_spacing_m', 7.0)
        self.declare_parameter('truth_topic', '/eland/obstacle_truth')
        # Written by scripts/gen_world.py when it placed the models. Reading it
        # rather than re-deriving the same layout from the same seed is the
        # whole point: two programs that each compute where the mobs are will
        # eventually disagree, and the disagreement will be silent -- models
        # standing in one place, poses commanded to another.
        self.declare_parameter('mob_layout_file', '')

        gp = self.get_parameter
        self._enabled = gp('enable').value
        self._world = gp('world_name').value
        rate = float(gp('update_rate_hz').value)
        self._person_kind = gp('person_kind').value
        self._mode = gp('vehicle_mode').value

        # One list, built from the same numbers gen_world.py used to place
        # them. Vehicles first, then people: the truth topic is a PoseArray
        # with no names in it, so the order is the contract, and it has to be
        # written down in exactly one place.
        self._movers = []
        layout = self._load_layout(gp('mob_layout_file').value)
        if layout:
            self._movers = layout
            self.get_logger().info(
                f'{len(layout)} mob loaded from the generated layout')
        else:
            self._movers = self._from_parameters(gp)

        self._gz = GzNode()
        self._service = f'/world/{self._world}/set_pose'

        # Sim time, from Gazebo's own statistics topic. Both obstacles are
        # placed on this clock rather than the wall clock so a run is
        # reproducible even if the real-time factor sags: the vehicle is where
        # the scenario says it is at sim second N, not at wall second N.
        self._sim_time = None
        self._real_time = None
        self._rtf_mark = None
        self._gz.subscribe(WorldStatistics, f'/world/{self._world}/stats',
                           self._on_stats)

        self._truth_pub = self.create_publisher(
            PoseArray, gp('truth_topic').value, 10)

        if not self._enabled:
            self.get_logger().warn(
                'obstacle_driver disabled by parameter; the world still '
                'contains whatever gen_world.py last wrote')
            return

        self.create_timer(1.0 / rate, self._tick)
        self.create_timer(10.0, self._log_rtf)
        for m in self._movers:
            self.get_logger().info(
                f"{'driving' if m['driven'] else 'tracking'} {m['name']} "
                f"{[round(v, 1) for v in m['start']]} -> "
                f"{[round(v, 1) for v in m['goal']]} at {m['speed']} m/s "
                f"({self._mode}), {m['leg_time']:.1f} s per leg, "
                f"phase {m['phase']:.2f}")

    def _from_parameters(self, gp):
        movers = []
        movers += self._build(
            kind='vehicle',
            name=gp('vehicle_name').value,
            count=int(gp('vehicle_count').value),
            start=list(gp('vehicle_start').value),
            goal=list(gp('vehicle_goal').value),
            speed=float(gp('vehicle_speed').value),
            spacing=float(gp('vehicle_spacing_m').value),
            z=float(gp('vehicle_size').value[2]) / 2.0,
            driven=True)
        movers += self._build(
            kind='person',
            name=gp('person_name').value,
            count=int(gp('person_count').value),
            start=list(gp('person_start').value),
            goal=list(gp('person_goal').value),
            speed=float(gp('person_speed').value),
            spacing=float(gp('person_spacing_m').value),
            # 0.9 m: half of the 1.8 m cylinder, so it stands on the ground
            # rather than half-buried, matching the static people.
            z=0.9,
            # An actor is driven by its own script; these commands would be
            # ignored, and the published truth is then nominal rather than
            # commanded.
            driven=self._person_kind == 'model')
        return movers

    def _load_layout(self, path):
        """Movers straight from the file the world was written from.

        Falls back to the parameter rule when there is no file: a fresh
        checkout that has not run the generator yet still starts.
        """
        if not path:
            path = os.path.join(
                os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                'worlds', 'mob_layout.yaml')
            # Installed packages keep the worlds under share/, not next to the
            # python module, so try that too before giving up.
            if not os.path.exists(path):
                try:
                    from ament_index_python.packages import get_package_share_directory
                    path = os.path.join(get_package_share_directory('eland_sim'),
                                        'worlds', 'mob_layout.yaml')
                except Exception:  # noqa: BLE001
                    return []
        if not os.path.exists(path):
            return []
        try:
            import yaml
            with open(path, 'r', encoding='utf-8') as handle:
                doc = yaml.safe_load(handle) or {}
        except Exception as exc:  # noqa: BLE001
            self.get_logger().warning(f'mob layout unreadable ({exc})')
            return []

        movers = []
        count = len(doc.get('mobs', []))
        for i, mob in enumerate(doc.get('mobs', [])):
            start = [float(v) for v in mob['start']]
            goal = [float(v) for v in mob['goal']]
            speed = float(mob['speed'])
            dist = math.hypot(goal[0] - start[0], goal[1] - start[1])
            movers.append({
                'kind': mob['kind'],
                'name': mob['name'],
                'start': start,
                'goal': goal,
                'speed': speed,
                'z': float(mob['z']),
                # An actor drives itself; everything else is teleported.
                'driven': mob['kind'] != 'person' or self._person_kind == 'model',
                'leg_time': dist / speed if speed > 0 else 0.0,
                'yaw_out': math.atan2(goal[1] - start[1], goal[0] - start[0]),
                # Spread the phases so a drawn scenario is traffic rather than
                # a starting grid.
                'phase': i / count if count else 0.0,
            })
        if doc.get('seed') is not None:
            self.get_logger().info(f'mob layout seed {doc["seed"]}')
        return movers

    # --------------------------------------------------------------- movers

    @staticmethod
    def _build(kind, name, count, start, goal, speed, spacing, z, driven):
        """Spread `count` obstacles along one configured leg.

        Obstacle 0 runs the leg as written; each one after it is pushed
        `spacing` metres to the side, alternating so the group stays centred
        on the route rather than drifting off it. This has to match
        gen_world.py, which placed the models -- the two are kept in step by
        both reading the same parameters and applying the same rule, and the
        rule is small enough to state twice rather than share a module for.

        Each also gets a phase offset, so a row of obstacles does not march in
        lockstep: with three vehicles on a 20 s leg they cross the map roughly
        seven seconds apart, which is a scenario rather than a formation.
        """
        movers = []
        count = max(0, int(count))
        for i in range(count):
            if i == 0:
                s0, g0 = list(start), list(goal)
            else:
                step = ((i + 1) // 2) * (1 if i % 2 else -1)
                heading = math.atan2(goal[1] - start[1], goal[0] - start[0])
                nx, ny = -math.sin(heading), math.cos(heading)
                off = step * spacing
                s0 = [start[0] + nx * off, start[1] + ny * off]
                g0 = [goal[0] + nx * off, goal[1] + ny * off]
            dist = math.hypot(g0[0] - s0[0], g0[1] - s0[1])
            movers.append({
                'kind': kind,
                'name': f'{name}_{i}',
                'start': s0,
                'goal': g0,
                'speed': speed,
                'z': z,
                'driven': driven,
                'leg_time': dist / speed if speed > 0 else 0.0,
                'yaw_out': math.atan2(g0[1] - s0[1], g0[0] - s0[0]),
                'phase': i / count if count else 0.0,
            })
        return movers

    def _pose_at(self, mover, t):
        """Where `mover` is at sim time t, as (x, y, yaw)."""
        leg = mover['leg_time']
        if leg <= 0.0:
            return mover['start'][0], mover['start'][1], mover['yaw_out']

        # The phase offset is in whole cycles, so it shifts the obstacle along
        # its own route rather than changing the route.
        t = t + mover['phase'] * 2.0 * leg
        if self._mode == 'pingpong':
            phase = (t % (2.0 * leg)) / leg
            if phase <= 1.0:
                frac, yaw = phase, mover['yaw_out']
            else:
                frac, yaw = 2.0 - phase, mover['yaw_out'] + math.pi
        else:
            frac = min(t / leg, 1.0)
            yaw = mover['yaw_out']

        x = mover['start'][0] + (mover['goal'][0] - mover['start'][0]) * frac
        y = mover['start'][1] + (mover['goal'][1] - mover['start'][1]) * frac
        return x, y, yaw

    # ------------------------------------------------------------------ gz io

    def _on_stats(self, msg):
        self._sim_time = msg.sim_time.sec + msg.sim_time.nsec * 1e-9
        self._real_time = msg.real_time.sec + msg.real_time.nsec * 1e-9

    def _log_rtf(self):
        """Report the real-time factor, because every speed in this system is
        quoted against one of two clocks and they are not the same one.

        The obstacles move on sim time -- so does the aircraft, so that is the
        clock the scenario is physically defined in. The perception chain
        stamps its frames with wall time, so tracker_node's velocities come
        out scaled by the real-time factor. Measured here rather than assumed,
        because on this machine the factor is well below 1 and a reader
        comparing an estimated 1.5 m/s against a configured 3.0 m/s deserves
        to see why before concluding the estimator is broken.
        """
        if self._sim_time is None or self._real_time is None:
            return
        if self._rtf_mark is None:
            self._rtf_mark = (self._sim_time, self._real_time)
            return
        d_sim = self._sim_time - self._rtf_mark[0]
        d_real = self._real_time - self._rtf_mark[1]
        self._rtf_mark = (self._sim_time, self._real_time)
        if d_real > 0.0:
            self.get_logger().info(
                f'real-time factor {d_sim / d_real:.2f} '
                f'(sim {self._sim_time:.1f} s); obstacles advance on sim time, '
                f'so their speed in wall-clock terms is that factor times the '
                f'configured value')

    def _set_pose(self, name, x, y, z, yaw):
        req = GzPose()
        req.name = name
        req.position.x = x
        req.position.y = y
        req.position.z = z
        qz, qw = _yaw_to_quat(yaw)
        req.orientation.z = qz
        req.orientation.w = qw
        ok, _ = self._gz.request(self._service, req, GzPose, Boolean, 200)
        return ok

    def _tick(self):
        if self._sim_time is None:
            # No world statistics yet. Placing the obstacles on the wall clock
            # in the meantime would start the scenario at an offset nobody
            # asked for, so they stay at their spawn poses until Gazebo speaks.
            return
        poses = []
        for mover in self._movers:
            x, y, yaw = self._pose_at(mover, self._sim_time)
            poses.append((x, y, yaw))
            if mover['driven']:
                self._set_pose(mover['name'], x, y, mover['z'], yaw)
        self._publish_truth(poses)

    def _publish_truth(self, poses):
        """Every obstacle, in `self._movers` order: vehicles first, then
        people. A PoseArray has no names in it, so the order is the contract,
        and it is stated in exactly two places -- here and where the list is
        built. Adding a message type for a topic that exists only to be
        plotted afterwards is not worth a new dependency in eland_msgs.
        """
        msg = PoseArray()
        msg.header.stamp = self.get_clock().now().to_msg()
        msg.header.frame_id = 'map'
        for mover, (x, y, yaw) in zip(self._movers, poses):
            pose = RosPose()
            pose.position.x = x
            pose.position.y = y
            pose.position.z = mover['z']
            qz, qw = _yaw_to_quat(yaw)
            pose.orientation.z, pose.orientation.w = qz, qw
            msg.poses.append(pose)
        self._truth_pub.publish(msg)


def main():
    rclpy.init()
    node = ObstacleDriver()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.try_shutdown()


if __name__ == '__main__':
    main()
