#!/usr/bin/env python3
"""Surface heights of the existing open-field world, for ground truth.

Reads src/eland_sim/worlds/eland_test.sdf.in (never writes it) and writes
src/eland_sim/worlds/veri/acik_alan.yaml in the format tools/veri/dunya.py
reads. Only collision geometry counts -- it is what the aircraft can touch:
the ponds are visual-only, so the physical ground under them is the plane at
z = 0. Each static model becomes one surface: its footprint (rotated box or
disc) and the height of its top.

Moving obstacles are not surfaces; their truth is /eland/obstacle_truth.
Re-run after editing the template.
"""
import math
import os
import re
import xml.etree.ElementTree as ET

import yaml

WS = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(WS, 'src', 'eland_sim', 'worlds', 'eland_test.sdf.in')
OUT = os.path.join(WS, 'src', 'eland_sim', 'worlds', 'veri', 'acik_alan.yaml')
LANDABLE_LABELS = {1, 2}       # taxonomy index + 1: safe-soft, safe-hard


def floats(text, n):
    vals = [float(v) for v in (text or '').split()] + [0.0] * n
    return vals[:n]


def main():
    text = open(SRC).read()
    # Comments hold "--" and the generator's marker; neither is XML.
    text = re.sub(r'<!--.*?-->', '', text, flags=re.S).replace('@DYNAMIC_OBSTACLES@', '')
    world = ET.fromstring(text).find('world')
    yuzeyler = []
    for m in world.findall('model'):
        if (m.findtext('static') or '').strip() != 'true':
            continue
        mx, my, mz, _, _, myaw = floats(m.findtext('pose'), 6)
        labels = [int(p.findtext('label')) for p in m.findall('plugin')
                  if p.findtext('label')]
        boxes, discs, top = [], [], None
        for link in m.findall('link'):
            lx, ly, lz = floats(link.findtext('pose'), 3)
            for col in link.findall('collision'):
                cx, cy, cz = floats(col.findtext('pose'), 3)
                g = col.find('geometry')
                if g is None:
                    continue
                ox = mx + (lx + cx) * math.cos(myaw) - (ly + cy) * math.sin(myaw)
                oy = my + (lx + cx) * math.sin(myaw) + (ly + cy) * math.cos(myaw)
                oz = mz + lz + cz
                if g.find('box') is not None:
                    sx, sy, sz = floats(g.find('box').findtext('size'), 3)
                    boxes.append([round(ox, 3), round(oy, 3), round(myaw, 4),
                                  round(sx, 3), round(sy, 3)])
                    t = oz + sz / 2.0
                elif g.find('cylinder') is not None:
                    r = float(g.find('cylinder').findtext('radius'))
                    ln = float(g.find('cylinder').findtext('length'))
                    discs.append([round(ox, 3), round(oy, 3), round(r, 3)])
                    t = oz + ln / 2.0
                else:
                    continue           # the ground plane
                top = t if top is None else max(top, t)
        if top is None:
            continue
        yuzeyler.append({
            'ad': m.get('name'), 'z': round(top, 3),
            'inilebilir': bool(labels) and labels[0] in LANDABLE_LABELS,
            'kutular': boxes, 'daireler': discs,
        })
    doc = {
        'dunya_id': 'acik_alan', 'gz_world': 'eland_test',
        'aciklama': 'mevcut acik alan dunyasi; eland_test.sdf.in carpisma geometrisinden',
        'zemin_z': 0.0, 'hedef': None, 'yuzeyler': yuzeyler,
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as f:
        f.write('# Generated by tools/veri/acik_alan_yuzey.py from eland_test.sdf.in.\n')
        yaml.safe_dump(doc, f, sort_keys=False, allow_unicode=True)
    print(f'{len(yuzeyler)} yuzey -> {OUT}')


if __name__ == '__main__':
    main()
