#!/usr/bin/env python3
"""Island worlds for the data-collection task (Asama 2). New files only.

    tools/veri/dunya_uret.py sabit [--ruzgar V --ruzgar-yon DEG]
    tools/veri/dunya_uret.py rastgele --tohum-bas 2001 --sayi 30 [--ruzgar V]

Every world is a field of grass islands in non-landable ground. The ground is
TERRAIN_HAZARD (class 2): not landable, but not a hazard class either, so a
site owes it only the 2 m class-seam margin, not the 3 m SORA separation that
water or structure would demand (decided 2026-10-03; with water, islands under
~6 m could never produce a candidate).

Each world gets a yaml next to it with the ground truth the recorder needs:
surface heights, the target island's area/centre/shape, the start conditions
drawn from the seed, the wind, and the moving people. tools/veri/dunya.py
reads it.

Fixed worlds (sabit) go to src/eland_sim/worlds/veri/, random ones to
~/eland_veri/dunyalar/. A world named NAME is NAME.sdf and its gz world is
also called NAME, because PX4 opens <worlds>/$PX4_GZ_WORLD.sdf.

Geometry notes, measured against the detector's own rules (r_fit 1 m,
r_class_edge 2 m on a 0.2 m grid):
  * an island narrower than ~4.4 m has no cell 2 m from its seam, so W1
    (4x4) and random islands under ~4.4 m produce no candidate -- kept as
    "no site" examples, the mode then times out and descends blind;
  * W6's L arms are 6 m wide for the same reason (4 m arms are unselectable);
  * W8's centre obstacle is also non-hazard class, otherwise the 3 m SORA
    separation from it and the 2 m seam margin leave nothing on a 10x10 m
    island.
"""
import argparse
import math
import os
import random
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
WS = os.path.dirname(os.path.dirname(HERE))
SABIT_DIR = os.path.join(WS, 'src', 'eland_sim', 'worlds', 'veri')
RASTGELE_DIR = os.path.join(os.path.expanduser('~'), 'eland_veri', 'dunyalar')
sys.path.insert(0, os.path.join(WS, 'src', 'eland_sim', 'scripts'))
import gen_world  # noqa: E402  -- reused read-only for the person model block

LABEL = {'grass': 1, 'terrain': 3}   # taxonomy index + 1 (gen_world / template)
SLAB = 0.02                          # same 2 cm slabs as the template's patches
GRASS_RGB = ('0.28 0.52 0.18 1', '0.34 0.62 0.22 1')
TERRAIN_RGB = ('0.33 0.30 0.20 1', '0.42 0.38 0.25 1')

# PX4's server.config, verbatim. A world that declares any world plugin is
# loaded with its own list instead of the server config, so a wind world has
# to carry the whole set or PX4 loses physics, sensors and the camera.
PX4_PLUGINS = """    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-contact-system" name="gz::sim::systems::Contact"/>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>
    <plugin filename="gz-sim-air-pressure-system" name="gz::sim::systems::AirPressure"/>
    <plugin filename="gz-sim-air-speed-system" name="gz::sim::systems::AirSpeed"/>
    <plugin filename="gz-sim-apply-link-wrench-system" name="gz::sim::systems::ApplyLinkWrench"/>
    <plugin filename="gz-sim-navsat-system" name="gz::sim::systems::NavSat"/>
    <plugin filename="gz-sim-magnetometer-system" name="gz::sim::systems::Magnetometer"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="libOpticalFlowSystem.so" name="custom::OpticalFlowSystem"/>
    <plugin filename="libGstCameraSystem.so" name="custom::GstCameraSystem"/>
"""

HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by tools/veri/dunya_uret.py -- do not edit; re-run the generator.
     {aciklama} -->
<sdf version="1.9">
  <world name="{ad}">
    <physics type="ode">
      <max_step_size>0.004</max_step_size>
      <real_time_factor>1.0</real_time_factor>
      <real_time_update_rate>250</real_time_update_rate>
    </physics>
    <gravity>0 0 -9.8</gravity>
    <magnetic_field>6e-06 2.3e-05 -4.2e-05</magnetic_field>
    <atmosphere type="adiabatic"/>
    <scene>
      <grid>false</grid>
      <ambient>0.4 0.4 0.4 1</ambient>
      <background>0.7 0.7 0.7 1</background>
      <shadows>true</shadows>
    </scene>
{eklentiler}
    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>1 1</size></plane></geometry>
          <surface><friction><ode/></friction><bounce/><contact/></surface>
        </collision>
        <visual name="visual">
          <geometry><plane><normal>0 0 1</normal><size>500 500</size></plane></geometry>
          <material><ambient>{t_amb}</ambient><diffuse>{t_dif}</diffuse>
            <specular>0.05 0.05 0.05 1</specular></material>
        </visual>
      </link>
      <plugin filename="gz-sim-label-system" name="gz::sim::systems::Label">
        <label>{zemin_label}</label>
      </plugin>
    </model>
"""

FOOTER = """
    <light name="sunUTC" type="directional">
      <pose>0 0 500 0 -0 0</pose>
      <cast_shadows>true</cast_shadows>
      <intensity>1</intensity>
      <direction>0.001 0.625 -0.78</direction>
      <diffuse>0.904 0.904 0.904 1</diffuse>
      <specular>0.271 0.271 0.271 1</specular>
      <attenuation><range>2000</range><linear>0</linear><constant>1</constant>
        <quadratic>0</quadratic></attenuation>
      <spot><inner_angle>0</inner_angle><outer_angle>0</outer_angle><falloff>0</falloff></spot>
    </light>
{ruzgar}
    <spherical_coordinates>
      <surface_model>EARTH_WGS84</surface_model>
      <world_frame_orientation>ENU</world_frame_orientation>
      <latitude_deg>47.397971057728974</latitude_deg>
      <longitude_deg> 8.546163739800146</longitude_deg>
      <elevation>0</elevation>
    </spherical_coordinates>
  </world>
</sdf>
"""


def box(name, cx, cy, cz, sx, sy, sz, label, rgb):
    return f"""    <model name="{name}">
      <static>true</static>
      <pose>{cx:.3f} {cy:.3f} {cz:.3f} 0 0 0</pose>
      <link name="link">
        <collision name="collision"><geometry><box><size>{sx:.3f} {sy:.3f} {sz:.3f}</size></box></geometry></collision>
        <visual name="visual"><geometry><box><size>{sx:.3f} {sy:.3f} {sz:.3f}</size></box></geometry>
          <material><ambient>{rgb[0]}</ambient><diffuse>{rgb[1]}</diffuse></material></visual>
      </link>
      <plugin filename="gz-sim-label-system" name="gz::sim::systems::Label"><label>{label}</label></plugin>
    </model>
"""


def disc(name, cx, cy, cz, r, sz, label, rgb):
    return f"""    <model name="{name}">
      <static>true</static>
      <pose>{cx:.3f} {cy:.3f} {cz:.3f} 0 0 0</pose>
      <link name="link">
        <collision name="collision"><geometry><cylinder><radius>{r:.3f}</radius><length>{sz:.3f}</length></cylinder></geometry></collision>
        <visual name="visual"><geometry><cylinder><radius>{r:.3f}</radius><length>{sz:.3f}</length></cylinder></geometry>
          <material><ambient>{rgb[0]}</ambient><diffuse>{rgb[1]}</diffuse></material></visual>
      </link>
      <plugin filename="gz-sim-label-system" name="gz::sim::systems::Label"><label>{label}</label></plugin>
    </model>
"""


def rect_area(rects):
    return sum(abs(x1 - x0) * abs(y1 - y0) for x0, y0, x1, y1 in rects)


# ------------------------------------------------------------------ islands
def island(kind, cx, cy, **k):
    """Island description: rectangles/discs in world coordinates, top height,
    landable area, and the models that draw it."""
    z = k.get('taban', 0.0)
    top = z + SLAB
    models, rects, discs = [], [], []
    holes = []
    if kind == 'kare':
        sx, sy = k['sx'], k['sy']
        rects = [[cx - sx / 2, cy - sy / 2, cx + sx / 2, cy + sy / 2]]
    elif kind == 'L':
        s, w = k['s'], k['kol']
        x0, y0 = cx - s / 2, cy - s / 2
        rects = [[x0, y0, x0 + s, y0 + w],            # bottom arm, full width
                 [x0, y0 + w, x0 + w, y0 + s]]        # left arm, above it
    elif kind == 'daire':
        discs = [[cx, cy, k['d'] / 2]]
    for i, (x0, y0, x1, y1) in enumerate(rects):
        models.append(box(f'ada_{i}', (x0 + x1) / 2, (y0 + y1) / 2, z + SLAB / 2,
                          x1 - x0, y1 - y0, SLAB, LABEL['grass'], GRASS_RGB))
    for i, (x, y, r) in enumerate(discs):
        models.append(disc(f'ada_d{i}', x, y, z + SLAB / 2, r, SLAB,
                           LABEL['grass'], GRASS_RGB))
    area = rect_area(rects) + sum(math.pi * r * r for _, _, r in discs)
    if k.get('engel'):
        e = k['engel']
        h = 0.5
        models.append(box('engel', cx, cy, top + h / 2, e, e, h, LABEL['terrain'], TERRAIN_RGB))
        holes = [[cx - e / 2, cy - e / 2, cx + e / 2, cy + e / 2]]
        area -= e * e
    return {
        'models': models,
        'yuzey': {'ad': 'ada', 'z': round(top, 3), 'inilebilir': True,
                  'sekil': kind, 'merkez': [round(cx, 3), round(cy, 3)],
                  'dikdortgenler': [[round(v, 3) for v in r] for r in rects],
                  'daireler': [[round(v, 3) for v in d] for d in discs],
                  'alan_m2': round(area, 3)},
        'engel': ({'ad': 'engel', 'z': round(top + 0.5, 3), 'inilebilir': False,
                   'dikdortgenler': holes} if holes else None),
    }


def start_conditions(rng, center, off_range):
    r = rng.uniform(*off_range)
    a = rng.uniform(0.0, 2.0 * math.pi)
    return {
        'irtifa_m': round(rng.uniform(10.0, 20.0), 1),
        'ofset_m': round(r, 2),
        'ofset_aci_deg': round(math.degrees(a), 1),
        'dogus': [round(center[0] + r * math.cos(a), 2),
                  round(center[1] + r * math.sin(a), 2), 0.0, 0.0, 0.0,
                  round(rng.uniform(-math.pi, math.pi), 3)],
    }


def people(rng, n, center, params, name_prefix='veri_kisi'):
    """n people walking straight lines that pass within 5 m of the island."""
    mobs, blocks = [], []
    for i in range(n):
        a = rng.uniform(0.0, math.pi)
        px = center[0] + rng.uniform(-5, 5)
        py = center[1] + rng.uniform(-5, 5)
        half = 15.0
        start = [round(px - half * math.cos(a), 2), round(py - half * math.sin(a), 2)]
        goal = [round(px + half * math.cos(a), 2), round(py + half * math.sin(a), 2)]
        name = f'{name_prefix}_{i}'
        mobs.append({'kind': 'person', 'name': name, 'start': start, 'goal': goal,
                     'speed': round(rng.uniform(0.8, 1.4), 2), 'z': 0.9})
        blocks.append(gen_world.person_model_block(params, name, start))
    return mobs, blocks


def wind_block(v, yon_deg, olcek):
    if v <= 0:
        return '', ''
    vx = v * math.cos(math.radians(yon_deg))
    vy = v * math.sin(math.radians(yon_deg))
    plugins = PX4_PLUGINS + f"""    <plugin filename="gz-sim-wind-effects-system" name="gz::sim::systems::WindEffects">
      <force_approximation_scaling_factor>{olcek}</force_approximation_scaling_factor>
    </plugin>
"""
    return plugins, f"""    <wind>
      <linear_velocity>{vx:.3f} {vy:.3f} 0</linear_velocity>
    </wind>"""


def write_world(name, desc, isl, extra_models, start, outdir, mobs=None,
                ruzgar=(0.0, 0.0, 1.0), platform=None):
    plugins, wind = wind_block(*ruzgar)
    parts = [HEADER.format(aciklama=desc, ad=name, eklentiler=plugins,
                           t_amb=TERRAIN_RGB[0], t_dif=TERRAIN_RGB[1],
                           zemin_label=LABEL['terrain'])]
    parts += extra_models + isl['models']
    parts.append(FOOTER.format(ruzgar=wind))
    os.makedirs(outdir, exist_ok=True)
    sdf = os.path.join(outdir, f'{name}.sdf')
    with open(sdf, 'w') as f:
        f.write(''.join(parts))
    yuzeyler = [isl['yuzey']]
    if isl['engel']:
        yuzeyler.append(isl['engel'])
    if platform:
        yuzeyler.append(platform)
    meta = {
        'dunya_id': name, 'gz_world': name, 'aciklama': desc,
        'zemin_z': 0.0, 'zemin_sinifi': 2, 'hedef': 'ada',
        'yuzeyler': yuzeyler, 'baslangic': start,
        'ruzgar': {'hiz_mps': ruzgar[0], 'yon_deg': ruzgar[1], 'olcek': ruzgar[2]},
        'hareketli_kisi': len(mobs or []),
    }
    if mobs is not None:
        layout = os.path.join(outdir, f'{name}.mobs.yaml')
        with open(layout, 'w') as f:
            yaml.safe_dump({'seed': None, 'mobs': mobs}, f, sort_keys=False)
        meta['mob_layout_file'] = layout
    with open(os.path.join(outdir, f'{name}.yaml'), 'w') as f:
        yaml.safe_dump(meta, f, sort_keys=False, allow_unicode=True)
    return sdf


def suffix(ruzgar):
    return f'_r{ruzgar[0]:g}'.replace('.', 'p') if ruzgar[0] > 0 else ''


def sabit(ruzgar, outdir):
    """W1-W8 from the task, island centre at the world origin."""
    defs = {
        'w1': ('4x4 m kare ada', dict(kind='kare', sx=4, sy=4)),
        'w2': ('6x6 m kare ada', dict(kind='kare', sx=6, sy=6)),
        'w3': ('10x10 m kare ada', dict(kind='kare', sx=10, sy=10)),
        'w4': ('20x20 m kare ada', dict(kind='kare', sx=20, sy=20)),
        'w5': ('10x10 m, zeminden 4 m yuksek platform', dict(kind='kare', sx=10, sy=10, taban=4.0)),
        'w6': ('10x10 m L sekli, kollar 6 m', dict(kind='L', s=10, kol=6)),
        'w7': ('10 m capli daire ada', dict(kind='daire', d=10)),
        'w8': ('10x10 m kare ada, ortasinda 2x2 m inilemez nesne', dict(kind='kare', sx=10, sy=10, engel=2.0)),
    }
    made = []
    for key, (desc, spec) in defs.items():
        rng = random.Random(f'sabit-{key}')
        kind = spec.pop('kind')
        isl = island(kind, 0.0, 0.0, **spec)
        extra, platform = [], None
        off = (0.0, 4.0)
        if spec.get('taban'):
            # The platform body: terrain class (not landable, not a hazard),
            # grass slab on top. Spawn off the platform so the EKF origin is
            # on the ground and the 4 m offset is what gets measured.
            extra.append(box('platform', 0.0, 0.0, 2.0, 10.0, 10.0, 4.0,
                             LABEL['terrain'], TERRAIN_RGB))
            platform = {'ad': 'platform', 'z': 4.0, 'inilebilir': False,
                        'dikdortgenler': [[-5.0, -5.0, 5.0, 5.0]]}
            off = (6.5, 8.0)
        start = start_conditions(rng, (0.0, 0.0), off)
        name = f'veri_{key}{suffix(ruzgar)}'
        made.append(write_world(name, desc, isl, extra, start, outdir,
                                mobs=[], ruzgar=ruzgar, platform=platform))
    return made


def rastgele(seed, ruzgar, outdir, params):
    rng = random.Random(seed)
    kind = rng.choice(['kare', 'L', 'daire'])
    cx, cy = round(rng.uniform(-8, 8), 2), round(rng.uniform(-8, 8), 2)
    if kind == 'kare':
        sx = rng.uniform(3, 20)
        sy = min(20.0, max(3.0, sx * rng.uniform(0.5, 2.0)))
        isl = island('kare', cx, cy, sx=round(sx, 2), sy=round(sy, 2))
        desc = f'rastgele kare ada {sx:.1f}x{sy:.1f} m'
    elif kind == 'L':
        s = rng.uniform(8, 20)
        kol = s * rng.uniform(0.4, 0.6)
        isl = island('L', cx, cy, s=round(s, 2), kol=round(kol, 2))
        desc = f'rastgele L ada {s:.1f} m, kol {kol:.1f} m'
    else:
        d = rng.uniform(3, 20)
        isl = island('daire', cx, cy, d=round(d, 2))
        desc = f'rastgele daire ada d={d:.1f} m'
    n = rng.randint(0, 2)
    mobs, blocks = people(rng, n, (cx, cy), params)
    start = start_conditions(rng, (cx, cy), (0.0, 4.0))
    name = f'veri_ada_t{seed}{suffix(ruzgar)}'
    return write_world(name, desc + f', {n} hareketli kisi', isl, blocks, start,
                       outdir, mobs=mobs, ruzgar=ruzgar)


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument('kip', choices=['sabit', 'rastgele'])
    p.add_argument('--tohum-bas', type=int, default=2001)
    p.add_argument('--sayi', type=int, default=30)
    p.add_argument('--ruzgar', type=float, default=0.0, help='m/s, 0 = yok')
    p.add_argument('--ruzgar-yon', type=float, default=45.0, help='derece, ENU, x eksenden')
    p.add_argument('--ruzgar-olcek', type=float, default=1.0,
                   help='WindEffects force_approximation_scaling_factor')
    p.add_argument('--cikti', default=None)
    a = p.parse_args()
    ruzgar = (a.ruzgar, a.ruzgar_yon, a.ruzgar_olcek)
    params = gen_world.load_params()
    if a.kip == 'sabit':
        made = sabit(ruzgar, a.cikti or SABIT_DIR)
    else:
        made = [rastgele(a.tohum_bas + i, ruzgar, a.cikti or RASTGELE_DIR, params)
                for i in range(a.sayi)]
    for m in made:
        print(m)


if __name__ == '__main__':
    main()
