#!/usr/bin/env python3
"""Generate x500_seg_cam_down_ruzgar: the aircraft with wind enabled.

Gazebo's WindEffects pushes only links that declare
<enable_wind>true</enable_wind>, and PX4's x500_base does not. SDFormat's
include parameters (experimental:params) can modify an element that exists
but cannot add one without a name attribute -- measured: "Could not find
element [enable_wind]" for modify, "missing a 'name' attribute" for add. So
the two PX4 models in the chain are derived here, with one line added and the
names changed, and regenerated from whatever PX4 version is installed:

    x500_base_ruzgar          PX4 x500_base + enable_wind on base_link
    x500_ruzgar               PX4 x500, including x500_base_ruzgar
    x500_seg_cam_down_ruzgar  our x500_seg_cam_down, including x500_ruzgar

PX4's own files are only read. Run again after a PX4 update.
"""
import os
import re

PX4_MODELS = os.path.expanduser('~/PX4-Autopilot/Tools/simulation/gz/models')
WS = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(WS, 'src', 'eland_sim', 'models')
NOTE = ('<!-- Generated by tools/veri/ruzgar_modeli_uret.py from {src}. '
        'Do not edit; re-run the generator. -->\n')


def write(name, sdf, desc):
    d = os.path.join(OUT, name)
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, 'model.sdf'), 'w') as f:
        f.write(sdf)
    with open(os.path.join(d, 'model.config'), 'w') as f:
        f.write(f"""<?xml version="1.0"?>
<model>
  <name>{name}</name>
  <version>1.0</version>
  <sdf version="1.9">model.sdf</sdf>
  <description>{desc}</description>
</model>
""")


def sub_once(pattern, repl, text, what):
    new, n = re.subn(pattern, repl, text, count=1)
    if n != 1:
        raise SystemExit(f'{what}: pattern not found -- PX4 model changed?')
    return new


def main():
    src = os.path.join(PX4_MODELS, 'x500_base', 'model.sdf')
    base = open(src).read()
    base = sub_once(r"<model name=['\"]x500_base['\"]>", "<model name='x500_base_ruzgar'>",
                    base, 'x500_base model name')
    base = sub_once(r'(<link name=["\']base_link["\']>)',
                    r'\1\n      <enable_wind>true</enable_wind>', base, 'base_link')
    base = base.replace('?>\n', '?>\n' + NOTE.format(src=src), 1)
    write('x500_base_ruzgar', base, 'PX4 x500_base with enable_wind on base_link.')

    src = os.path.join(PX4_MODELS, 'x500', 'model.sdf')
    x5 = open(src).read()
    x5 = sub_once(r"<model name=['\"]x500['\"]>", "<model name='x500_ruzgar'>", x5,
                  'x500 model name')
    x5 = sub_once(r'model://x500_base<', 'model://x500_base_ruzgar<', x5, 'x500 include')
    x5 = x5.replace('?>\n', '?>\n' + NOTE.format(src=src), 1)
    write('x500_ruzgar', x5, 'PX4 x500, including x500_base_ruzgar.')

    src = os.path.join(OUT, 'x500_seg_cam_down', 'model.sdf')
    seg = open(src).read()
    seg = sub_once(r"<model name=['\"]x500_seg_cam_down['\"]>",
                   "<model name='x500_seg_cam_down_ruzgar'>", seg, 'seg cam model name')
    seg = sub_once(r'<uri>x500</uri>', '<uri>x500_ruzgar</uri>', seg, 'seg cam include')
    seg = seg.replace('?>\n', '?>\n' + NOTE.format(src=src), 1)
    write('x500_seg_cam_down_ruzgar', seg,
          'x500_seg_cam_down with wind enabled on the body (data collection only).')
    print('x500_base_ruzgar, x500_ruzgar, x500_seg_cam_down_ruzgar ->', OUT)


if __name__ == '__main__':
    main()
